excluded:
  - DerivedData

disabled_rules:
  - orphaned_doc_comment
  - leading_whitespace

opt_in_rules:
  - indentation_width
  - force_unwrapping
  - multiline_arguments
  - redundant_type_annotation
  - force_try
  - operator_usage_whitespace

force_cast: warning

multiline_arguments:
  first_argument_location: next_line
  only_enforce_after_first_closure_on_first_line: true

trailing_whitespace:
  ignores_empty_lines: true
  ignores_comments: true

indentation_width:
  indentation_width: 4

vertical_whitespace:
  max_empty_lines: 2

line_length:
  warning: 180
  ignores_urls: true
  ignores_function_declarations: true
  ignores_comments: true

function_body_length:
    warning: 70

type_name:
  min_length: 3
  max_length:
    warning: 50
    error: 60
  excluded: iPhone
identifier_name:
  excluded:
    - i
    - id
    - x
    - y
    - z

custom_rules:
  array_constructor:
    name: "Array/Dictionary initializer"
    regex: '[let,var] .+ = (\[.+\]\(\))'
    capture_group: 1
    message: "Use explicit type annotation when initializing empty arrays and dictionaries"
    severity: warning

